# Generated by Django 2.2 on 2019-06-07 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=200, verbose_name='シーズン')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Season')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(blank=True, null=True, verbose_name='進行度')),
                ('speaker', models.CharField(max_length=200, verbose_name='発話者')),
                ('script', models.TextField(blank=True, max_length=1000, null=True, verbose_name='セリフ')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Title')),
            ],
        ),
    ]
