# Generated by Django 2.2 on 2019-06-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='url',
            field=models.URLField(default='', verbose_name='URL'),
        ),
    ]
