# Generated by Django 2.2 on 2019-06-22 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190621_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='script',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.Item'),
        ),
    ]
